#!/bin/bash

# get the current directories that we are running from
CURRENTDIR=$(pwd)

# then change to the home directory and create symlinks to the .dotfiles
# directory that we were originally in
cd ~
ln -s ${CURRENTDIR}/.vimrc .vimrc
ln -s ${CURRENTDIR}/.zshrc .zshrc
ln -s ${CURRENTDIR}/.tmux.conf .tmux.conf
