#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# plugins directory
SUDOPLUGIN="${BASEDIR}/dotbot-sudo/sudo.py"
OMNIPKGPLUGIN="${BASEDIR}/dotbot-omnipkg/omnipkg.py"

cd "${BASEDIR}"
git submodule update --quiet --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -d "${BASEDIR}" \
    -c "${CONFIG}" \
    -p "${SUDOPLUGIN}" \
    -p "${OMNIPKGPLUGIN}" \
    "${@}" 
