unstable_features = true
binop_separator = "Back"
enum_discrim_align_threshold = 20
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
single_line_if_else_max_width = 0
