# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# export useful information
export DOTFILES=/home/$USER/.dotfiles
# vim path information
export VIMRC=${DOTFILES}/vim/init.vim
export VIMPLUGINS=${DOTFILES}/vim/plugins
# zsh path information
export ZSHRC=${DOTFILES}/zsh/zshrc
export ZSHPATHFILE=${DOTFILES}/zsh/zshpath
# tmux path information
export TMUXRC=${DOTFILES}/tmux/tmux.conf
# kitty path information
export KITTYRC=${DOTFILES}/kitty/kitty.conf

# export path based on what in the zshpath file
# Removes leading and trailing white space
# Ignores any line beginning with #
# Ignores empty lines
# I currently have plans to work this further into a common path file +
# a system specific path file
export PATH=$(cat ${ZSHPATHFILE} | sed -e 's/^[ \t]//' | sed -e 's/[ \t]*$//' | sed -e '/^$/d' | grep -v '^#' | tr '\n' ':')

# keep backup path here just in case we manage to bodge the above
# otherwise we have to call programs with pull paths which is a pain
#export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# load plugin manager and oh-my-zsh
source ~/.antigen/antigen.zsh
antigen use oh-my-zsh

# theme
antigen theme romkatv/powerlevel10k

# antigen is finished
antigen apply

# instead of using cp use rsync instead
if hash rsync &> /dev/null
then
    alias cp="rsync -avz"
fi

# if nvim is installed then use it instead of vim
if hash nvim &> /dev/null
then
    alias vi="nvim"
    alias vim="nvim"
fi

# add symlinks for working with python
if hash python &> /dev/null
then
  alias py="python"
fi
if hash python3 &> /dev/null
then
  alias py3="python3"
fi

# if vimcat is installed then add ccat alias
if hash vimcat
then
  alias ccat="vimcat"
fi

# for accidental vim commands in terminal
alias :q='echo You are not editing a file, dummy'
alias :wq='echo You are not editing a file, dummy'


# add fzf into the mix
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# add some fzf config here

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# finally if we are not in tmux session then make a new one
if [ "$TMUX" = "" ]; then tmux attach || tmux new; fi
